### ISSUE TITLE
Add a new mission to test Soroban tx size upgrades

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/supercluster#100]
We should add a new mission that tests Soroban tx size upgrades and its impact on overlay. We should ensure the following:
* Adequate transaction load is generated on all ledgers (before and after the upgrade) to make sure overlay transaction flooding isn't impacted
* The mission(s) should try different upgrade sequences, e.g. upgrade protocol 19 to 20, increase soroban max tx size, decrease soroban max tx size, what happens if classic max tx size is greater that soroban max tx size, etc.
```[tasklist]
### Tasks
- [ ] upgrade protocol 19 to 20
- [ ] increase/decrease soroban max tx size
```

**Comment by anupsdf** [comment]
Related to https://github.com/stellar/supercluster/issues/106
