### ISSUE TITLE
Add test to verify that stellar-core works with two version of soroban env

### ISSUE THREAD

**Issue by anupsdf** [stellar/supercluster#105]
### What problem does your feature solve?
With introduction of Soroban in protocol version 20, stellar core will support multiple versions of soroban-env-host. These are referenced in [src/rust/Cargo.toml](https://github.com/stellar/stellar-core/blob/master/src/rust/Cargo.toml#L31) under soroban-env-host-curr and soroban-env-host-prev. However, we need an automated test that verifies this works and alerts us if a PR breaks multi versioning.

### What would you like to see?
Test should ensure that core can run both prev and curr version of Soroban env host and perform an upgrade.
Here is what we can verify,
- [ ] Build rs-soroban-env with vnext version (+1 from current) in[ meta.rs](https://github.com/anupsdf/rs-soroban-env/blob/main/soroban-env-common/src/meta.rs#L44)
- [ ] core can run two versions of env, curr and prev.
- [ ] Before an upgrade the prev version of env is used. Assert that call to env.ledger().protocol_version() returns the [current version](https://github.com/anupsdf/rs-soroban-env/blob/main/soroban-env-host/src/host.rs#L2952).
- [ ] After an upgrade to vnext version (+1), the curr version of env can be called. Assert that call to env.ledger().protocol_version() returns the new protocol version.

### What alternatives are there?
Open to suggestions.

**Comment by MonsieurNicolas** [comment]
We also need to somehow verify that a version of core that has two hosts attached to it can replay ledgers with both envs (for ledgers where both host support that version of the protocol).

We could run parallel catchup twice for this (once with the "curr" host, and another with the "next" host), but a better strategy might be to just add a way to replay ledgers with both curr and next: basically, apply a ledger with "curr", set aside the meta (but do not commit to the db), apply with "next" and compare that the meta matches (or do it at the op/host invocation level and compare not the meta, but whatever the host returns).

**Comment by sisuresh** [comment]
I wrote a Supercluster mission that applies Soroban transactions across protocol versions, and then brings up a node to do a complete catchup - https://github.com/stellar/supercluster/pull/130.

**Comment by sisuresh** [comment]
Will be closed by https://github.com/stellar/ops/issues/2918

**Comment by marta-lokhova** [comment]
This can be closed now, right? @sisuresh

**Comment by sisuresh** [comment]
Yeah this is done.
