### ISSUE TITLE
New missions to test Soroban transactions & upgrades end-to-end

### ISSUE THREAD

**Issue by mbsdf** [stellar/supercluster#106]

**Comment by dmkozh** [comment]
Some thoughts on the missions/functionality to add based on the loadgen suggestions mentioned here: https://github.com/stellar/stellar-core/issues/3706#issuecomment-1726531709

- Support a few distributions of Soroban traffic, with the goal of covering flooding/surge pricing/txset building (an observable signal would be delay/transaction exclusion rate)
  - Normal distribution of every resource
  - Extreme cases: max transactions only, min transactions only
  - 'Spiky' traffic with one of the dimensions at max and others either at low values or normally distributed
- Classic traffic: for the simpler cases and Soroban benchmarks we can omit the classic traffic, but for the proper load testing we need to generate classic traffic with full load
- Upgrade scenarios
  - 'Killswitch' mission with reduction the soroban tx count to 0 and back up to a reasonable value
  -  increase/decrease the transaction-level and ledger-level resource limits via network config upgrades, while generating load (this seems pretty involved from the core side, but it's one more reason to implement this in a reusable fashion for other use cases as well)

**Comment by dmkozh** [comment]
We still need to prepare the load tests (including classic traffic) in order to be able to calibrate the per-ledger network limits.

**Comment by SirTyson** [comment]
> We still need to prepare the load tests (including classic traffic) in order to be able to calibrate the per-ledger network limits.

We have a mixed load test in flight here: https://github.com/stellar/supercluster/pull/121.
What sort of test are you envisioning for calibrating per-ledger network limits? Do you want to increase limits until nodes fall out of sync to find an upper bound?

**Comment by dmkozh** [comment]
> Do you want to increase limits until nodes fall out of sync to find an upper bound?

Not really, I just want to do some load testing to figure out how much can we increase per-ledger limits without compromising the ledger close time, i.e. nothing extreme.

**Comment by SirTyson** [comment]
#155 should address this.

**Comment by marta-lokhova** [comment]
Resolved by https://github.com/stellar/supercluster/pull/164
