### ISSUE TITLE
Update `MixedImageNetworkSurvey` mission to set lower phase timeouts on old image when supported

### ISSUE THREAD

**Issue by bboston7** [stellar/supercluster#166]
#165 added a new mission `MixedImageNetworkSurvey` where `--old-image` was expected to be an image version that predates the addition of the time sliced network survey. Once the old stable image is expected to contain the new survey interface we should update [the `oldCoreSet`'s phase duration](https://github.com/stellar/supercluster/blob/99c5af664944ec8b0217b5789088dfca06c9af47/src/FSLibrary/MissionMixedImageNetworkSurvey.fs#L53) to match `newCoreSet`'s phase duration.

**Comment by marta-lokhova** [comment]
Depends on the release of v21.2.0
