### ISSUE TITLE
Formalize and publish performance evaluation methodology

### ISSUE THREAD

**Issue by marta-lokhova** [stellar/supercluster#170]
This issue tracks completing and documenting a performance evaluation framework to measure maximum theoretical throughput of the Stellar network. A couple of items here: 
* Complete https://github.com/stellar/supercluster/pull/164 which adds support for Soroban+classic load
* Open source and document various topologies to use for TPS tests
* Better document the existing (and new) TPS test, with steps and configurations needed to reproduce
* Include hardware/cloud recommendations

**Comment by bboston7** [comment]
I've got a few initial questions that'll help me with the docs:
1. Who is the intended audience for these docs? Devs? Users? Someone else?
2. Related to (1), do the docs need to cover setup of infrastructure required to support supercluster (such as how to install/configure kubernetes)? Or can we assume that the reader already knows how to do that?
3. I'm not sure what the hardware/cloud requirements are. Can someone please point me to those?

Also tagging @MonsieurNicolas and @anupsdf as they were in the slack thread that spawned this ticket.

**Comment by anupsdf** [comment]
The linked issue has more context around this but adding some information here,

> 1. Who is the intended audience for these docs? 
This is for anyone trying to benchmark various blockchains and verify the max TPS the chains claim to support. The docs here could allow anyone to verify that the published max TPS on Stellar network is accurate.

> 2. do the docs need to cover setup of infrastructure required to support supercluster?
Good point! We could add links to install any software used for the verification.

> 3. hardware/cloud requirements 
The benchmark tests can use high performance machines to support higher CPU and bandwidth

**Comment by anupsdf** [comment]
For maximum theoretical throughput of the Stellar network, we probably would not want to use the 50-50 blended traffic that is used in the max TPS mixed classic+Soroban mission. We can pick classic payment Ops.
