### ISSUE TITLE
NullReferenceException is possible due to unexpected result from a Kubernetes API call

### ISSUE THREAD

**Issue by sisuresh** [stellar/supercluster#20]
We've been seeing the exception below when changes are made to the cluster while supercluster is running. It looks like migrating running pods from one node to another can cause the exception.

```Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object. at StellarJobExec.checkPendingPodBuildup@190(StellarFormation self, FSharpRef`1 lastPodBuildupCheckTime, Unit unitVar0) in /supercluster/src/FSLibrary/StellarJobExec.fs:line 199```

The line that's throwing the exception - https://github.com/stellar/supercluster/blob/85191ba788c6ae18a2937d61b7cb28c5c25130bb/src/FSLibrary/StellarJobExec.fs#L199

It looks like `ListNamespacedPod` can return null in this scenario, which we don't expect. We should handle this here and everywhere else we call `ListNamespacedPod`. We should also make sure a pod migration doesn't disrupt supercluster once this `NullReferenceException` is fixed.

**Comment by marta-lokhova** [comment]
> We should also make sure a pod migration doesn't disrupt supercluster once this NullReferenceException is fixed.

Agreed, I think as part of this issue we should make sure that supercluster can gracefully handle situations where a worker it's using is shutdown (the crash described in this issue is due to a deprecated worker, but there might be other places)

**Comment by marta-lokhova** [comment]
@sisuresh I think we haven't encountered this for a while, so it is safe to close?

**Comment by sisuresh** [comment]
Yeah we can close this.
