### ISSUE TITLE
Tier1Perf completion

### ISSUE THREAD

**Issue by graydon** [stellar/supercluster#40]
The Tier1Perf mission in #26 is still somewhat unfinished. The goal is to have a mode (perhaps not its default, or perhaps recycling option flags or main processing path from the older `benchmark` top-level command of Supercluster) wherein it ramps up multiloadgen runs at higher and higher rates until they start failing, and then reports the maximum successful / sustained TPS rate.

**Comment by marta-lokhova** [comment]
@graydon I think we can close this?

**Comment by graydon** [comment]
Yep, thanks!
