### ISSUE TITLE
support traefik 2.x ingress configuration through CRDs

### ISSUE THREAD

**Issue by graydon** [stellar/supercluster#6]
Supercluster currently only knows how to configure the traefik ingress using a standard Kubernetes Ingress object. This worked for configuring traefik v1.x, but in traefik v2.x they have [changed things](https://doc.traefik.io/traefik/v2.0/providers/kubernetes-crd/#traefik-ingressroute-definition) somewhat dramatically. It now uses a custom resource definition for its own resource types.

To support this we need to [add a C# object for the custom resource](https://github.com/kubernetes-client/csharp/blob/master/examples/customResource/CustomResourceDefinition.cs) and figure out how to configure it the new way traefik wants. This will be fairly complex, and it will block us moving to newer versions of traefik and/or any newer kubernetes distributions that use traefik 2.x (in particular the [1.21.x series of k3s](https://github.com/k3s-io/k3s/releases) uses traefik v2.x)

**Comment by SirTyson** [comment]
Closing, we decided to move away from traefik.
